import "./globals.css";
import { Poppins } from "next/font/google";
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "600", "700"],
  variable: '--font-poppins',
});

export const metadata = {
  title: "cryptixon-dashboard",
  description: "Generated by create next app",
   icons: {
    icon: "/assets/images/cryptxion_logo.png", // or "/logo.png"
  },
};
import { Toaster } from "sonner";
export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={poppins.variable}>
        {children}
          <Toaster/>
      </body>
    </html>
  );
}
