
import "../globals.css";
import { Poppins } from "next/font/google";

import { AppSidebar } from "@/components/app-sidebar";
import { SidebarProvider, SidebarInset, } from "@/components/ui/sidebar";
import Navbar from "../components/navBar";
import Footer from "../components/Footer";
import { ThemeProvider } from "../Themeprovider";
import { Dialogs } from "../components/profile/Dialog";
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "600", "700"],
  variable: '--font-poppins',
});

export const metadata = {
  title: "cryptixon-dashboard",
  description: "Generated by create next app",
   icons: {
    icon: "/assets/images/cryptxion_logo.png", // or "/logo.png"
  },
};

export default function RootLayout({ children }) {
  return (

    <div>
      <ThemeProvider
       attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
      >
      <SidebarProvider>
      <AppSidebar />
      <SidebarInset>

      {/* navbar */}
       
   <Navbar/>

   {children}
  <Dialogs/>
     
      </SidebarInset>
    </SidebarProvider>
    <footer>
    <Footer/>
    </footer>
    </ThemeProvider>
      </div>
      
  );
}
  



